os: osx

osx_image: xcode8.3

language: node_js

node_js:
  - stable

env:
  matrix:
    - TEST_SCOPE: lint
    - TEST_SCOPE: desktop_unit
    - TEST_SCOPE: mobile_unit
    - TEST_SCOPE: gemini

matrix:
  fast_finish: true

install:
  - yarn install

before_script:
  - |
      if [ "${TEST_SCOPE}" == "gemini" ]; then
        curl -L https://gist.githubusercontent.com/teryaew/ab7c8a1c377ba0796f20a007a1d830eb/raw/sauce-connect.sh | bash
        cat .gemini.js
      fi

script:
  - if [ "${TEST_SCOPE}" == "lint" ]; then npm run lint; fi
  - if [ "${TEST_SCOPE}" == "desktop_unit" ]; then npm run test; fi
  - if [ "${TEST_SCOPE}" == "mobile_unit" ]; then MOBILE=1 npm run test; fi
  - if [ "${TEST_SCOPE}" == "gemini" ]; then npm run gemini; fi

after_success:
  - |
    if [ "${TRAVIS_BRANCH}" == "master" ]; then
      if [ "${TEST_SCOPE}" == "lint" ]; then
        sh ./tools/publish-styleguide.sh
      fi
      if [ "${TEST_SCOPE}" == "desktop_unit" ]; then
        sh ./tools/publish-styleguide-fantasy.sh
      fi
    fi

after_failure:
  - |
    if [ "${TEST_SCOPE}" == "gemini" ]; then
      sh ./tools/publish-gemini-report.sh
    fi
