dist: trusty

language: node_js

node_js:
  - '7.4.0'

env:
  matrix:
    - TEST_SCOPE: lint
    - TEST_SCOPE: desktop_unit
    - TEST_SCOPE: mobile_unit
    - TEST_SCOPE: gemini

matrix:
  fast_finish: true

before_install:
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn install

before_script:
  - greenkeeper-lockfile-update
  - |
    if [ "${TEST_SCOPE}" == "gemini" ]; then
      curl -L https://gist.githubusercontent.com/teryaew/ab7c8a1c377ba0796f20a007a1d830eb/raw/sauce-connect.sh | bash
      cat .gemini.js
    fi

script:
  - if [ "${TEST_SCOPE}" == "lint" ]; then yarn lint; fi
  - if [ "${TEST_SCOPE}" == "desktop_unit" ]; then yarn test; fi
  - if [ "${TEST_SCOPE}" == "mobile_unit" ]; then MOBILE=1 yarn test; fi
  - if [ "${TEST_SCOPE}" == "gemini" ]; then
      if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then
        export ALL_SIZES=1;
        yarn build-polyfills;
      fi;
      yarn gemini-ci;
    fi

after_script:
  - greenkeeper-lockfile-upload
  - |
    if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TEST_SCOPE}" == "lint" ] && [ -n "${TRAVIS_TAG}" ]; then
      yarn github-release;
      echo "GitHub Releases were successfully updated";
    fi
  - |
    if [ "${TEST_SCOPE}" == "gemini" ]; then
      kill -9 `lsof -i :4445 -t`
    fi

after_success:
  - |
    if [ "${TRAVIS_BRANCH}" == "master" ]; then
      if [ "${TEST_SCOPE}" == "lint" ]; then
        sh ./tools/publish-styleguide.sh
      fi
      if [ "${TEST_SCOPE}" == "desktop_unit" ]; then
        sh ./tools/publish-styleguide-fantasy.sh
      fi
    fi

after_failure:
  - |
    if [ "${TEST_SCOPE}" == "gemini" ]; then
      sh ./tools/publish-gemini-report.sh
    fi
